In [1]:
import torch

In [2]:
x = torch.tensor([10, 20, 30])

print(x)
print(x.shape)
print(x.ndim)

# row = x.unsqueeze(0)
# print(row.shape)
column = x.unsqueeze(1)

# print(row)
# print(row.shape)

print(column)
print(column.shape)

tensor([10, 20, 30])
torch.Size([3])
1
tensor([[10],
        [20],
        [30]])
torch.Size([3, 1])


In [3]:
x = torch.tensor([4, 8, 12, 16])
y = x.unsqueeze(1)
print(y)

tensor([[ 4],
        [ 8],
        [12],
        [16]])


In [4]:
lengths = torch.tensor([2, 4]).unsqueeze(1)
positions = torch.tensor([0, 1, 2, 3]).unsqueeze(0)
positions < lengths

tensor([[ True,  True, False, False],
        [ True,  True,  True,  True]])

In [5]:

x = torch.tensor([10, 20, 30])
print(x.shape)
x.unsqueeze(0)
print(x.shape)
x.unsqueeze(1)
print(x.shape)

torch.Size([3])
torch.Size([3])
torch.Size([3])


In [6]:


PAD_ID = 0

text_lengths = torch.tensor([3, 5], dtype=torch.long)
waveform_lengths = torch.tensor([7, 4], dtype=torch.long)
text = torch.full((2, 5), PAD_ID, dtype=torch.long)

print(f"text before padding :{text}")
text[0, :3] = torch.tensor([11, 12, 13])
text[1, :5] = torch.tensor([21, 22, 23, 24, 25])
print(f"text before padding :{text}")



waveform = torch.zeros((2, 7), dtype=torch.float32)
waveform[0, :7] = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7])
waveform[1, :4] = torch.tensor([1.0, 2.0, 3.0, 4.0])

print(f"wav :{waveform}")




text before padding :tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])
text before padding :tensor([[11, 12, 13,  0,  0],
        [21, 22, 23, 24, 25]])
wav :tensor([[0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000],
        [1.0000, 2.0000, 3.0000, 4.0000, 0.0000, 0.0000, 0.0000]])


In [7]:
def make_mask(lengths, max_length):
    positions = torch.arange(
        max_length,
        device=lengths.device
    )

    positions = positions.unsqueeze(0)  # [1, T]
    lengths = lengths.unsqueeze(1)      # [B, 1]

    mask = positions < lengths             # [B, T]

    mask = mask.unsqueeze(1)             # [B, 1, T]
    return mask

In [8]:
text_mask = make_mask(text_lengths, 5)
waveform_mask = make_mask(waveform_lengths, 7)

print(text_mask)
print(text_mask.shape)
print(waveform_mask)
print(waveform_mask.shape)

tensor([[[ True,  True,  True, False, False]],

        [[ True,  True,  True,  True,  True]]])
torch.Size([2, 1, 5])
tensor([[[ True,  True,  True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True, False, False, False]]])
torch.Size([2, 1, 7])


In [9]:
features = torch.arange(2 * 3 * 5, dtype=torch.float32).reshape(2, 3, 5)

masked_features = features * text_mask.to(features.dtype)


In [10]:
print("features.shape:", features.shape)
print("text_mask.shape:", text_mask.shape)
print("masked_features.shape:", masked_features.shape)

features.shape: torch.Size([2, 3, 5])
text_mask.shape: torch.Size([2, 1, 5])
masked_features.shape: torch.Size([2, 3, 5])


In [11]:
import torch
x =  torch.arange(5)
x

tensor([0, 1, 2, 3, 4])

In [12]:
y = x.unsqueeze(0)
y

tensor([[0, 1, 2, 3, 4]])

## Practice 2  

Waveform
   ↓ STFT
Complex spectrogram
   ↓ magnitude
Linear-frequency magnitude spectrogram
   ↓ mel filter bank
Mel spectrogram
   ↓ clamp and logarithm
Log-mel spectrogram

In [13]:
sample_rate = 22050
n_fft       = 1024
win_length  = 1024
hop_length  = 256
n_mels      = 80

waveform:    [B,T_wav]
STFT:        [B,513,T_frames]
mel:         [B,80,T_frames]

In [14]:
(n_fft/sample_rate) * 1000

46.439909297052154

In [15]:
waveform = torch.rand((1, 22050), dtype=torch.float32) * 2 - 1

In [16]:
hann_window = torch.hann_window(
    1024,
    device=waveform.device,
    dtype=waveform.dtype,
)

In [17]:
stft_result = torch.stft(
    waveform,
    n_fft=1024,
    win_length=1024,
    hop_length=256,
    window=hann_window,
    center=True,
    return_complex=True,
)

Frequency bins


In [ ]:
# n_fft # 2 + 1
# = 1024 #// 2 + 1
# = 512 + 1
# = 513

n_fft = 513

: 

Padding